// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdptuoxiwgpcmugocexy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcHR1b3hpd2dwY211Z29jZXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTgxODEsImV4cCI6MjA2OTY3NDE4MX0.4gJHWBO8wt0Ex8hCsKuSoF1iwbSYGKLkFcwQv2A_3eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});